import { Inter } from 'next/font/google'
import type { Children } from '@/modules/interface'
import './globals.css'
import Header from '@/components/header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'eSport Recruitment',
  description: 'Generated by create next app'
}

const RootLayout: React.FC<Children> = ({ children }) => (
  <html lang='en' data-theme='dark' className={inter.className}>
    <body>
      <Header />
      {children}
    </body>
  </html>
)

export default RootLayout
